[project]
name = "problemsolver-new"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cachetools>=6.2.0",
    "flask>=3.1.2",
    "flask-cors>=6.0.1",
    "ftfy>=6.3.1",
    "gunicorn>=23.0.0",
    "openai>=1.102.0",
    "psycopg2-binary>=2.9.10",
    "python-dotenv>=1.0.1",
]

[dependency-groups]
dev = [
    "black>=25.1.0",
    "mypy>=2.3.0",
    "pylint>=4.0.6",
    "ruff>=0.13.0",
    "types-cachetools>=7.0.0.20260713",
    "types-psycopg2>=2.9.21.20260712",
]
